# Generated by Django 2.0.1 on 2018-01-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
